[tool.poetry]
name = "python-formatting"
version = "0.1.0"
description = "Sample project to setup code testing and formatting tools"
authors = ["Sadik Bakiu <sadik@data-max.io>"]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "^3.7"
isort = "^5.11.5"
pre-commit = "^2.21.0"
pytest = "^7.2.1"
pytest-cov = "4.0.0"
flake8 = "5.0.4"
black = "22.12.0"
sqlfluff = "1.2.1"
sqlfluff-templater-dbt = "^1.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
multi_line_output = 3
src_paths = ["isort", "test"]
line_length = 120

[tool.sqlfluff.core]
templater = "dbt"
dialect = "ansi"

[tool.sqlfluff.rules]
tab_space_size = 4
max_line_length = 120

[tool.sqlfluff.templater.dbt]
project_dir = "dbt/dbt_test_project"
profiles_dir = "dbt"
profile = "default"
target = "test"

[tool.flake8]
exclude = [".git", "__pycache__"]
max-line-length = 120

[tool.pytest]
pythonpath = "."