name: CI

on:
  pull_request:
  push:
    branches:
      - develop
      - main

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  linting:
    needs: setup
    uses: ./.github/workflows/pre-commit.yaml

  testing:
    needs: linting
    uses: ./.github/workflows/pytest.yaml
