name: Run pre-commit

on:
  workflow_call:


jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Linting
        run: |
          pip install poetry
          poetry install
          poetry run pre-commit run --all-files